// 1000 hand-curated 'Did you know' aviation facts
// CSV source delivered by the user; categories spread across types, parts,
// safety, navigation, history, passengers, ATC, words/culture, airports.
export const EXTRA_FACTS: string[] = [
  "Did you know swept wings help aircraft fly efficiently at higher speeds?",
  "Did you know many modern approaches use GPS instead of older ground-based navigation aids?",
  "Did you know accident investigations look for chains of causes, not just one simple mistake?",
  "Did you know pilots say “Charlie” for the letter C in the ICAO spelling alphabet?",
  "Did you know wing area matters because larger wings can support more weight at slower speeds?",
  "Did you know pressure altitude is used in performance calculations?",
  "Did you know a nose-heavy airplane can handle differently from a tail-heavy one?",
  "Did you know regional jets connect smaller markets with airline networks?",
  "Did you know tower controllers manage takeoffs, landings, and runway crossings at towered airports?",
  "Did you know a heading is the direction the nose is pointed?",
  "Did you know green navigation lights are on the right side of an aircraft?",
  "Did you know high-altitude aircraft need special designs for thin air and cold temperatures?",
  "Did you know pilots brief passengers differently depending on the aircraft and operation?",
  "Did you know the cabin chime can be a crew signal, not just a passenger call?",
  "Did you know the Douglas C-47 was a military version of the DC-3 family?",
  "Did you know DME gives distance from a navigation station?",
  "Did you know crop dusters are specialized agricultural airplanes built for low-level spraying?",
  "Did you know turbofan engines move a lot of air around the engine core, not just through it?",
  "Did you know triplanes have three wing levels and are strongly associated with early aviation?",
  "Did you know FOD can be anything from a loose screw to a dropped pen cap, and crews take it seriously?",
  "Did you know a headwind blows toward the nose of the airplane?",
  "Did you know carbon fiber composites are strong for their weight?",
  "Did you know pilots brief takeoff and landing plans before busy phases of flight?",
  "Did you know stratus clouds form layers that can cover wide areas?",
  "Did you know recline etiquette is not an official aircraft system, but passengers definitely have opinions about it?",
  "Did you know QNH is an altimeter setting that makes the altimeter read elevation when on the ground?",
  "Did you know flight attendants use interphones to talk with each other and the cockpit?",
  "Did you know galley ovens warm meals but usually do not cook from scratch like a restaurant kitchen?",
  "Did you know “hold short” means stop before crossing a runway or taxiway point?",
  "Did you know twin-engine airplanes can keep flying after one engine fails if operated within limits?",
  "Did you know cargo and passenger flights often share the same airports and runways?",
  "Did you know pilots say “Uniform” for the letter U in the ICAO spelling alphabet?",
  "Did you know VTOL means vertical takeoff and landing?",
  "Did you know some waypoints have fun names chosen by procedure designers?",
  "Did you know pilots say “Echo” for the letter E in the ICAO spelling alphabet?",
  "Did you know “negative” means no on the radio?",
  "Did you know airlines build schedules around aircraft utilization because parked airplanes do not earn revenue?",
  "Did you know full-motion simulators can make a pilot feel acceleration cues without leaving the building?",
  "Did you know turboprops are popular for shorter routes because they can be efficient at lower speeds?",
  "Did you know controllers may speak quickly at busy airports, which is why pilots practice listening skills?",
  "Did you know airliners often cruise high because thinner air can reduce drag?",
  "Did you know airport beacons can help pilots spot an airport at night?",
  "Did you know modern twin-engine airliners handle many long routes once flown by four-engine jets?",
  "Did you know white tail lights help show the rear of many aircraft at night?",
  "Did you know cumulus clouds often look puffy because they form in rising air?",
  "Did you know titanium is used where strength and heat resistance matter?",
  "Did you know weather radar helps crews see areas of precipitation and storm activity ahead?",
  "Did you know rudder pedals control the rudder and often help steer on the ground?",
  "Did you know floatplanes have floats attached under the fuselage?",
  "Did you know aircraft tires are designed for big loads, fast rotation, and hard braking?",
  "Did you know a frequency change tells a pilot to switch radios to a new controller?",
  "Did you know “plane spotting” means watching, photographing, or logging aircraft?",
  "Did you know airplanes bank to turn, rather than turning like a car on a road?",
  "Did you know taxi lights help pilots see while moving around the airport surface?",
  "Did you know a diversion means a flight lands somewhere other than the planned destination?",
  "Did you know exit row seats come with extra responsibility, not just extra legroom?",
  "Did you know the DC-3 was famous for reliability and range in its era?",
  "Did you know aerobatic airplanes are built to handle high loads and unusual attitudes?",
  "Did you know Runway 22 points roughly toward 220 degrees on a compass, which is generally southwest?",
  "Did you know a load sheet helps confirm weight and balance before departure?",
  "Did you know baggage tags use barcodes and airport codes to help route luggage?",
  "Did you know belt loaders lift bags from carts into cargo holds?",
  "Did you know a standby passenger is waiting for an available seat on a flight?",
  "Did you know IFR flight plans help ATC manage aircraft through clouds and controlled airspace?",
  "Did you know “line up and wait” lets an aircraft enter the runway but wait before takeoff?",
  "Did you know collision avoidance is everyone’s job in aviation?",
  "Did you know airports inspect pavement and lights regularly because small problems can become big aviation problems?",
  "Did you know flying with a strong tailwind can save time and fuel?",
  "Did you know Runway 03 points roughly toward 30 degrees on a compass, which is generally northeast?",
  "Did you know the four main forces on an airplane are lift, weight, thrust, and drag?",
  "Did you know clear-air turbulence can happen even when there are no visible clouds nearby?",
  "Did you know tie-down ropes or chains keep parked small airplanes from moving in strong wind?",
  "Did you know departure procedures help aircraft leave busy or obstacle-filled areas safely?",
  "Did you know some airports still use stairs and buses instead of jet bridges?",
  "Did you know marker beacons were once common parts of instrument landing systems?",
  "Did you know aviation learns from incidents as well as accidents?",
  "Did you know GPS changed aviation navigation by making precise satellite positioning widely available?",
  "Did you know aircraft evacuation rules are designed around getting people out quickly in survivable situations?",
  "Did you know most passenger jets cruise below the speed of sound?",
  "Did you know hydraulic leaks are taken seriously because hydraulics power important systems?",
  "Did you know fabric-covered aircraft are still maintained and flown today?",
  "Did you know ADS-B can help aircraft and controllers see traffic more accurately?",
  "Did you know windshield wipers exist on many aircraft because rain still matters at the windshield?",
  "Did you know life rafts may be carried for certain overwater operations?",
  "Did you know Runway 01 points roughly toward 10 degrees on a compass, which is generally north-northeast?",
  "Did you know tour aircraft are often chosen for good visibility and passenger access?",
  "Did you know aircraft batteries are handled carefully because they store a lot of energy?",
  "Did you know marshalling wands help ground crews guide aircraft when hand signals are needed?",
  "Did you know AIRMETs warn pilots about widespread but generally less severe weather hazards?",
  "Did you know a gentle landing flare increases the airplane’s nose-up attitude just before touchdown?",
  "Did you know the term “clipper” became associated with Pan Am’s famous flying boats?",
  "Did you know Runway 11 points roughly toward 110 degrees on a compass, which is generally east-southeast?",
  "Did you know pilots use standard phraseology to reduce misunderstandings?",
  "Did you know early pilots often followed roads, rivers, and railroads before modern navigation systems existed?",
  "Did you know short wings can be efficient at high speed, while long wings are great for gliding?",
  "Did you know pilots say “India” for the letter I in the ICAO spelling alphabet?",
  "Did you know cockpit flows are memorized patterns that help pilots set switches efficiently?",
  "Did you know safety cards are aircraft-specific, so the pictures matter?",
  "Did you know airport baggage carts are the little trains of luggage you see crossing the ramp?",
  "Did you know oxygen systems support crew and passengers if pressurization is lost?",
  "Did you know the de Havilland Comet was the world’s first jet airliner to enter service?",
  "Did you know clearance delivery gives route clearances at many busy airports?",
  "Did you know pilots say “Tango” for the letter T in the ICAO spelling alphabet?",
  "Did you know pilots say “Yankee” for the letter Y in the ICAO spelling alphabet?",
  "Did you know life vests are placed where passengers can reach them on overwater-equipped flights?",
  "Did you know “greaser” is pilot slang for an especially smooth landing?",
  "Did you know pilots say “Oscar” for the letter O in the ICAO spelling alphabet?",
  "Did you know a biplane has two main wings stacked one above the other?",
  "Did you know FBO stands for fixed-base operator, a service provider at many general aviation airports?",
  "Did you know pilotage means navigating by looking outside at landmarks?",
  "Did you know supersonic aircraft must handle shock waves that subsonic aircraft avoid?",
  "Did you know Runway 30 points roughly toward 300 degrees on a compass, which is generally northwest?",
  "Did you know a taxi clearance can include a route made of several taxiway letters?",
  "Did you know a glider has no engine but can stay up using rising air?",
  "Did you know “pan-pan” is used for urgent situations that are serious but not immediately life-threatening?",
  "Did you know some airliners can dump fuel to reduce weight before an urgent landing?",
  "Did you know a stopway can provide extra pavement for rejected takeoffs at some airports?",
  "Did you know cabin lights may be dimmed at night so passengers’ eyes adjust before takeoff or landing?",
  "Did you know taxiways are like airport roads for aircraft?",
  "Did you know control sticks are used in many airplanes to control pitch and roll?",
  "Did you know satellite communication helps aircraft stay connected over oceans and remote areas?",
  "Did you know fuel planning includes trip fuel, reserve fuel, and sometimes alternate fuel?",
  "Did you know early airmail routes helped prove airplanes could do useful commercial work?",
  "Did you know flight recorders are often bright orange, even though people call them black boxes?",
  "Did you know a passenger manifest lists who is onboard a flight?",
  "Did you know KLAX is the ICAO code for Los Angeles International Airport?",
  "Did you know airline aircraft receive routine inspections between deeper scheduled maintenance checks?",
  "Did you know early airline travel could be loud, cold, and bumpy compared with modern flights?",
  "Did you know “tree” can be used for 3 in aviation radio pronunciation?",
  "Did you know oceanic flights use special procedures because radar and radio coverage can be limited far from land?",
  "Did you know alternate airports give flights backup options when destination weather is uncertain?",
  "Did you know anti-collision lights help make aircraft more conspicuous?",
  "Did you know westbound U.S. VFR cruising altitudes commonly use even thousands plus 500 feet when the rule applies?",
  "Did you know ATIS broadcasts airport weather and runway information on a loop at many airports?",
  "Did you know a connection means changing flights before reaching the final destination?",
  "Did you know aluminum became popular in aircraft because it is light and workable?",
  "Did you know landing lights brightly illuminate the runway area during takeoff and landing?",
  "Did you know airliners can descend for many miles with reduced thrust to save fuel?",
  "Did you know ground controllers help aircraft move safely around taxiways?",
  "Did you know hybrid-electric aircraft mix electric systems with fuel-powered systems?",
  "Did you know remove-before-flight streamers are bright so they are hard to miss?",
  "Did you know pilots say “Alfa” for the letter A in the ICAO spelling alphabet?",
  "Did you know pilots say “Whiskey” for the letter W in the ICAO spelling alphabet?",
  "Did you know some airports have trains that connect terminals behind security?",
  "Did you know the Red Arrows, Blue Angels, and Thunderbirds are famous military demonstration teams?",
  "Did you know many countries use different registration prefixes for civil aircraft?",
  "Did you know frost on a wing can be a big deal even when it looks thin?",
  "Did you know a tail number is an aircraft registration number?",
  "Did you know the longest runways are often found at high, hot, or heavy-aircraft airports?",
  "Did you know the P-51 Mustang is one of the best-known fighter aircraft of World War II?",
  "Did you know STOL aircraft are designed for short takeoff and landing performance?",
  "Did you know pilots say “Bravo” for the letter B in the ICAO spelling alphabet?",
  "Did you know rime ice often looks rough and milky?",
  "Did you know a course is the intended path over the ground?",
  "Did you know belly cargo is cargo carried underneath passengers on regular airline flights?",
  "Did you know sectional charts show airports, airspace, terrain, and navigation aids for visual flying?",
  "Did you know some escape slides can also work as flotation devices?",
  "Did you know runway threshold lights show green to landing aircraft?",
  "Did you know Pan Am flying boats made ocean travel feel futuristic in the 1930s?",
  "Did you know seaplanes use floats or boat-like hulls to operate on water?",
  "Did you know a flight number can stay the same even if the aircraft assigned to it changes?",
  "Did you know fuel gauges help track usable fuel, but pilots also plan fuel carefully before flight?",
  "Did you know lavatory smoke detectors are serious safety equipment?",
  "Did you know “Cactus” was once used by America West and later associated with US Airways?",
  "Did you know “flare” sounds dramatic, but it is just the landing transition before touchdown?",
  "Did you know radar changed air traffic control by letting controllers see aircraft beyond visual range?",
  "Did you know readbacks are a normal part of aviation radio discipline?",
  "Did you know useful load includes people, baggage, cargo, and usable fuel on many small aircraft?",
  "Did you know one pilot may fly while the other pilot handles radios and checklists?",
  "Did you know the rudder is the vertical tail control surface that helps the airplane yaw left or right?",
  "Did you know aircraft washing is maintenance, not just vanity?",
  "Did you know pilots use charts that are specially designed for aviation navigation?",
  "Did you know a tailwind blows from behind the airplane?",
  "Did you know red airport signs with white letters usually mean a mandatory instruction area?",
  "Did you know Harriet Quimby was the first woman in the United States to earn a pilot certificate?",
  "Did you know multi-engine airplanes have two or more engines?",
  "Did you know the Boeing 747 first flew in 1969?",
  "Did you know pitot tubes measure ram air pressure for the airspeed system?",
  "Did you know boarding passes include codes that help airlines match passengers, flights, seats, and boarding groups?",
  "Did you know “up-gauge” means using a larger aircraft on a route?",
  "Did you know student pilots often learn in small, simple airplanes before moving to faster aircraft?",
  "Did you know airport fire stations are positioned for fast aircraft emergency response?",
  "Did you know the heading indicator helps pilots hold direction without staring only at a compass?",
  "Did you know small changes in airflow can make big changes in lift at the wing?",
  "Did you know airport terminals are designed to move people, bags, crew, food, fuel, and aircraft all at once?",
  "Did you know barometric pressure changes can make an altimeter read differently if not adjusted?",
  "Did you know “base” is the traffic-pattern leg before final?",
  "Did you know pilots practice memory items for the rare situations that require immediate action?",
  "Did you know safety cards use pictures because passengers may speak different languages?",
  "Did you know 121.5 MHz is an international aviation emergency frequency?",
  "Did you know anti-ice systems help keep ice from building on important surfaces?",
  "Did you know drag is not always bad; pilots use drag to slow down and descend?",
  "Did you know crew resource management teaches crews to communicate clearly and catch errors early?",
  "Did you know RNP is a navigation standard that includes onboard performance monitoring?",
  "Did you know altimeter settings help pilots match their altimeters to local pressure?",
  "Did you know pilots usually cannot leave the cockpit just because someone wants a selfie in flight?",
  "Did you know the jet engine was developed independently by pioneers in different countries?",
  "Did you know the big fan at the front of many jet engines provides much of the thrust?",
  "Did you know Runway 12 points roughly toward 120 degrees on a compass, which is generally southeast?",
  "Did you know VFR means visual flight rules?",
  "Did you know drone pilots must follow airspace rules just like other aviation users?",
  "Did you know the radome is the nose cover that often protects weather radar antennas?",
  "Did you know headsets help pilots hear radios over engine and airflow noise?",
  "Did you know flight attendants are safety professionals first and service professionals too?",
  "Did you know “butter” is modern slang for a very smooth landing?",
  "Did you know control yokes look a little like steering wheels but control pitch and roll?",
  "Did you know “blue side up” is a simple pilot joke about keeping the sky above you?",
  "Did you know airplanes are designed with margins so normal flights stay well away from aerodynamic limits?",
  "Did you know a tractor propeller sits in front and pulls the aircraft forward?",
  "Did you know hydrant fuel systems let large airports fuel aircraft from underground pipes?",
  "Did you know “ferry flight” moves an aircraft without normal passengers or cargo?",
  "Did you know wind correction angle is the small heading adjustment used to stay on course in wind?",
  "Did you know a pusher propeller sits behind the engine and pushes the aircraft forward?",
  "Did you know Runway 32 points roughly toward 320 degrees on a compass, which is generally northwest?",
  "Did you know rear seats may feel more movement in turbulence on some aircraft?",
  "Did you know solar-powered aircraft have flown using energy from sunlight?",
  "Did you know airplane windows are small partly because pressurized fuselages like strong structures?",
  "Did you know TCAS can warn pilots about nearby aircraft and suggest climb or descent maneuvers?",
  "Did you know emergency exits are counted, marked, lit, and briefed for a reason?",
  "Did you know arrival procedures help organize traffic flowing into busy airports?",
  "Did you know an engine cowling is a removable cover around an engine?",
  "Did you know standard pressure is used above transition altitude or transition level in many airspace systems?",
  "Did you know GPS receivers use satellites to help aircraft know where they are?",
  "Did you know thermals are rising bubbles of warm air that glider pilots love?",
  "Did you know oxygen bottles must be handled carefully because high-pressure oxygen supports combustion?",
  "Did you know a propeller blade acts like an airfoil moving in a circle?",
  "Did you know modern airline seats are certified to withstand strong crash forces?",
  "Did you know pilots can use a crab angle to track the runway centerline in a crosswind?",
  "Did you know small aircraft give heavy jets extra room because wake turbulence can linger?",
  "Did you know airlines use boarding groups to control crowd flow and overhead bin pressure?",
  "Did you know air has weight, even though it feels invisible on a calm day?",
  "Did you know pilots say “Golf” for the letter G in the ICAO spelling alphabet?",
  "Did you know oversold flights happen because airlines predict some passengers may not show up?",
  "Did you know pilots use standard callouts so both crew members know what is happening?",
  "Did you know the “golden age of aviation” often refers to the 1920s and 1930s?",
  "Did you know oxygen masks drop in airliner cabins if cabin pressure becomes too low?",
  "Did you know wide-body airliners usually have two aisles?",
  "Did you know airplane cabins are divided into zones to help crews manage service and safety?",
  "Did you know the fastest boarding method is surprisingly hard because people, bags, groups, and seats all interact?",
  "Did you know flying into a strong headwind can make a flight arrive later even if the airplane works normally?",
  "Did you know flying boats use the fuselage itself like a boat hull?",
  "Did you know non-destructive testing can find cracks without destroying the part being inspected?",
  "Did you know terrain awareness systems warn pilots when the ground is getting too close?",
  "Did you know a jet bridge can move up, down, left, and right to match the aircraft door?",
  "Did you know the turn coordinator helps show rate of turn and coordination in many small airplanes?",
  "Did you know cabin pressurization systems make high-altitude flight comfortable for passengers and crew?",
  "Did you know a wing shape designed for flight is called an airfoil?",
  "Did you know ATIS often includes weather, runway, and approach information for a specific airport?",
  "Did you know a steep turn usually needs more lift than straight-and-level flight?",
  "Did you know Runway 14 points roughly toward 140 degrees on a compass, which is generally southeast?",
  "Did you know airplanes can climb because thrust and lift together overcome weight and drag?",
  "Did you know simulators can recreate bad weather, system failures, and unusual airport approaches?",
  "Did you know fuel trucks can deliver fuel directly to aircraft at many airports?",
  "Did you know temporary runway closures can happen for snow, construction, inspections, or wildlife?",
  "Did you know outflow valves help control cabin pressure by letting air leave the cabin at a managed rate?",
  "Did you know wing walking was a real aviation stunt in the barnstorming era?",
  "Did you know all-white PAPI lights usually mean the aircraft is high on approach?",
  "Did you know the 1903 Wright Flyer was damaged by wind after its successful flights?",
  "Did you know pressurization loads make the fuselage behave a bit like a carefully engineered soda can?",
  "Did you know Runway 33 points roughly toward 330 degrees on a compass, which is generally north-northwest?",
  "Did you know experimental aircraft can include prototypes, research aircraft, and amateur-built airplanes?",
  "Did you know the Supermarine Spitfire is closely associated with the Battle of Britain?",
  "Did you know radio-controlled aircraft were popular long before consumer camera drones?",
  "Did you know indicated altitude is what the altimeter shows?",
  "Did you know pilots repeat important ATC instructions so both sides can catch mistakes?",
  "Did you know seat belts are required for occupants during many takeoff and landing operations?",
  "Did you know runway numbers are usually based on magnetic compass direction rounded to the nearest ten degrees?",
  "Did you know long-haul crews may have hidden rest areas on some aircraft?",
  "Did you know “ramp rat” is a lighthearted nickname sometimes used for ramp workers?",
  "Did you know airport baggage systems can be miles of belts, scanners, diverters, and carts?",
  "Did you know rubber from aircraft tires can build up on runway touchdown zones?",
  "Did you know Runway 02 points roughly toward 20 degrees on a compass, which is generally north-northeast?",
  "Did you know groundspeed is how fast an airplane is moving over the earth?",
  "Did you know pilots can ask ATC to speak slower if needed?",
  "Did you know parallel runways can use L, C, and R to mean left, center, and right?",
  "Did you know center of gravity matters because it affects stability and control?",
  "Did you know Class D airspace often surrounds airports with operating control towers?",
  "Did you know fairings smooth airflow around bumps, joints, and landing gear parts?",
  "Did you know hangars protect aircraft from weather, sun, and surprise bird decorations?",
  "Did you know magnetic north and true north are not exactly the same?",
  "Did you know airport moving walkways are basically mini conveyor belts for tired travelers?",
  "Did you know the Cessna 172 became one of the most-produced airplanes in history?",
  "Did you know runway numbers do not tell pilots how long the runway is?",
  "Did you know microbursts are powerful downdrafts that can be hazardous near airports?",
  "Did you know yellow taxiway centerlines guide aircraft around the airfield?",
  "Did you know lithium batteries are treated carefully in aviation because damaged batteries can overheat?",
  "Did you know non-towered airports still have traffic patterns and radio etiquette?",
  "Did you know thunderstorms are avoided because they can contain turbulence, hail, lightning, and strong vertical winds?",
  "Did you know engine covers and pitot covers protect parked aircraft, but they must be removed before flight?",
  "Did you know banner tow airplanes pull advertising banners through the sky?",
  "Did you know cabin air is refreshed regularly during flight?",
  "Did you know heated leading edges help many jets fight ice on wings or engine inlets?",
  "Did you know tray tables must be stowed for takeoff and landing so exits and movement stay clear?",
  "Did you know crew rest compartments can be above or below the main passenger cabin on certain wide-body jets?",
  "Did you know cockpit doors on airliners are reinforced and controlled for security?",
  "Did you know ELTs help rescuers locate an aircraft after certain accidents?",
  "Did you know airplanes usually take off and land into the wind when they can?",
  "Did you know emergency locator transmitters can send a distress signal after certain crashes?",
  "Did you know aviation English is designed to be clear even between speakers with different accents?",
  "Did you know special-use airspace can warn pilots about military training, restricted areas, or other activities?",
  "Did you know lift is created by pressure differences and airflow turning around the wing?",
  "Did you know your checked bag may ride in a container called a ULD on many wide-body aircraft?",
  "Did you know airline dispatchers share operational control with captains in some systems?",
  "Did you know pilot-controlled lighting lets pilots turn on some airport lights by keying the radio?",
  "Did you know ceilings describe how low the cloud layer is above an airport?",
  "Did you know four-engine airliners were once common for long oceanic routes?",
  "Did you know “unable” is a standard word pilots can use when they cannot safely accept an instruction?",
  "Did you know some historic airplanes still fly because volunteers and specialists keep them maintained?",
  "Did you know pilots monitor each other during airline operations to catch slips early?",
  "Did you know a stall warning tells a pilot the wing is getting close to an aerodynamic stall?",
  "Did you know SIGMETs warn pilots about significant meteorological hazards?",
  "Did you know cleaning crews can reset a cabin in minutes at busy airports?",
  "Did you know airliner air is commonly filtered with high-efficiency filters?",
  "Did you know wide-body aircraft changed airline economics by carrying more passengers per flight?",
  "Did you know high-elevation airports can require longer takeoff distances?",
  "Did you know birds are a real aviation hazard, so airports manage wildlife carefully?",
  "Did you know airline route planning considers demand, aircraft range, airport fees, crews, maintenance, and weather?",
  "Did you know balanced field length is a takeoff planning concept for multi-engine aircraft?",
  "Did you know a transponder replies to radar or surveillance systems so controllers can identify the aircraft?",
  "Did you know a flight plan tells the system where an aircraft intends to go?",
  "Did you know airliners often route around storms rather than through them?",
  "Did you know pilots say “Mike” for the letter M in the ICAO spelling alphabet?",
  "Did you know a sleek airplane is not automatically efficient if it cannot carry the required payload?",
  "Did you know ADS-B equipment can broadcast an aircraft’s position to improve traffic awareness?",
  "Did you know the wing area can offer a smoother ride because it is closer to the aircraft’s center of lift?",
  "Did you know airport identifiers can be three letters for passengers and four letters for pilots and flight planning?",
  "Did you know jet bridges became common because they protect passengers from weather while boarding?",
  "Did you know weather radar shows precipitation better than clear-air turbulence?",
  "Did you know sterile cockpit rules reduce distractions during critical phases of airline operations?",
  "Did you know EGLL is the ICAO code for London Heathrow?",
  "Did you know an exhaust nozzle helps direct engine gases rearward to make thrust?",
  "Did you know the altimeter uses air pressure to estimate altitude?",
  "Did you know maximum takeoff weight is the heaviest an aircraft is allowed to weigh at takeoff?",
  "Did you know pilots often write down clearances to avoid relying only on memory?",
  "Did you know aircraft corrosion prevention matters because airplanes live in weather, salt, and humidity?",
  "Did you know “wet lease” means an aircraft is leased with crew and other operational support?",
  "Did you know diversions can happen for weather, medical needs, mechanical issues, or airport closures?",
  "Did you know minimum connection times are planned, but weather and airport layout can make tight connections risky?",
  "Did you know taxiway edge lights are commonly blue?",
  "Did you know blast pads are paved areas beyond some runway ends that are not for normal landing?",
  "Did you know pilots practice rejected takeoffs in simulators because the real thing is rare and time-critical?",
  "Did you know alternators and generators provide electrical power after engines are running?",
  "Did you know anti-icing fluid can help keep snow or ice from sticking for a limited time before takeoff?",
  "Did you know the non-movement area includes many ramps where ramp controllers or ground crews may coordinate traffic?",
  "Did you know the first Wright Flyer flight traveled about 120 feet?",
  "Did you know boarding early does not make the airplane fly faster, but it can improve bin odds?",
  "Did you know air traffic controllers separate aircraft and organize the flow of traffic?",
  "Did you know clouds can show where the air is rising, sinking, or full of moisture?",
  "Did you know the Lockheed SR-71 Blackbird was famous for flying very fast and very high?",
  "Did you know required equipment depends on the type of flight, aircraft, and rules being used?",
  "Did you know pilots say “Papa” for the letter P in the ICAO spelling alphabet?",
  "Did you know the U-2 aircraft was designed for very high-altitude reconnaissance?",
  "Did you know flight simulators changed pilot training by making rare emergencies safe to practice?",
  "Did you know the two ends of the same runway have numbers about 18 apart because they face opposite directions?",
  "Did you know a green-and-white rotating beacon commonly identifies a civilian land airport in the U.S.",
  "Did you know ailerons are small movable panels near the wingtips that help the airplane roll left or right?",
  "Did you know position lights help aircraft be seen at night?",
  "Did you know tires can deflate through fuse plugs if overheated, helping reduce explosion risk?",
  "Did you know piston airplanes use engines that work a bit like car engines, but built for aviation?",
  "Did you know Amelia Earhart flew solo across the Atlantic in 1932?",
  "Did you know pilots say “X-ray” for the letter X in the ICAO spelling alphabet?",
  "Did you know a flight release includes operational details for an airline flight?",
  "Did you know “ident” makes an aircraft’s radar target stand out for a controller?",
  "Did you know jet engine inlets are shaped to guide smooth air into the engine?",
  "Did you know instrument charts show procedures pilots can fly when they cannot rely only on outside views?",
  "Did you know paper airplanes are tiny gliders, even if they are not certified for snack delivery?",
  "Did you know FOD checks protect aircraft from loose objects on ramps and runways?",
  "Did you know holding patterns are racetrack-shaped paths used to delay aircraft safely?",
  "Did you know pilots say “Zulu” for the letter Z in the ICAO spelling alphabet?",
  "Did you know air sickness bags became a practical cabin item in the early days of passenger aviation?",
  "Did you know orange cones and reflective vests are part of the airport ground choreography?",
  "Did you know pilots use “see and avoid” when flying visually, but they also use radios, lights, and traffic systems to help?",
  "Did you know Runway 13 points roughly toward 130 degrees on a compass, which is generally southeast?",
  "Did you know bugs on wings can affect airflow on some aircraft?",
  "Did you know turbulence is usually uncomfortable, not dangerous, for properly flown airliners?",
  "Did you know brake temperatures are monitored because heavy braking creates a lot of heat?",
  "Did you know maintenance crews use task cards to make complex work repeatable?",
  "Did you know engine pylons attach many jet engines to the wings?",
  "Did you know angle of attack is the angle between the wing and the oncoming airflow?",
  "Did you know passenger briefings exist because people forget exits when they are surprised?",
  "Did you know “keep the shiny side up” is another aviation way of saying fly safely?",
  "Did you know the fuselage is the main body of the airplane?",
  "Did you know aircraft brakes turn motion into heat, just like car brakes, but on a much bigger scale?",
  "Did you know Zulu time is aviation slang for UTC time?",
  "Did you know “fife” can be used for 5 in aviation radio pronunciation?",
  "Did you know a propeller spinner is the smooth nose cone on many propeller hubs?",
  "Did you know IMC means instrument meteorological conditions?",
  "Did you know a helicopter rotor blade is also a kind of spinning wing?",
  "Did you know composite materials can make aircraft structures lighter and resistant to corrosion?",
  "Did you know a clearway is an obstacle-free area beyond a runway that can count in takeoff planning?",
  "Did you know KJFK is the ICAO code for New York’s John F. Kennedy International Airport?",
  "Did you know aircraft separation can be measured vertically, laterally, longitudinally, or visually depending on the operation?",
  "Did you know all-red PAPI lights usually mean the aircraft is low on approach?",
  "Did you know VHF radios are used for most routine pilot-controller voice communications?",
  "Did you know pilots call hot-and-high airport conditions a performance challenge?",
  "Did you know a localizer provides left-right guidance for an instrument landing?",
  "Did you know a stable airplane tends to return toward trimmed flight after small disturbances?",
  "Did you know pilots can squawk 7700 to signal a general emergency on a transponder?",
  "Did you know Class B airspace often surrounds the busiest airports?",
  "Did you know “numbers” can mean the runway threshold markings pilots aim near during landing?",
  "Did you know simulator training lets crews practice emergencies without risking an aircraft?",
  "Did you know an instrument rating trains pilots to fly by instruments when outside visibility is limited?",
  "Did you know a dispatcher helps plan and monitor many airline flights?",
  "Did you know Runway 27 points roughly toward 270 degrees on a compass, which is generally west?",
  "Did you know “tail number” is another name for an aircraft registration?",
  "Did you know hydraulic systems use pressurized fluid to move heavy controls, brakes, or landing gear?",
  "Did you know foreign object debris on a runway or ramp is called FOD?",
  "Did you know an aircraft livery is its paint scheme and branding?",
  "Did you know paint protects aircraft structure as well as making it look good?",
  "Did you know mist and fog differ by visibility?",
  "Did you know wind direction in aviation weather is usually given as the direction the wind comes from?",
  "Did you know retractable gear can fold into the airplane to reduce drag in flight?",
  "Did you know before V1, crews may reject takeoff for serious issues according to procedures?",
  "Did you know magnetos can provide spark for piston engines without relying entirely on the aircraft battery?",
  "Did you know lightning can strike airplanes, and aircraft are designed to safely conduct it around the structure?",
  "Did you know a control tower manages traffic on runways and nearby airspace at many airports?",
  "Did you know Runway 08 points roughly toward 80 degrees on a compass, which is generally east?",
  "Did you know carburetor heat helps prevent or clear ice in some carbureted piston engines?",
  "Did you know aircraft weight includes passengers, bags, cargo, fuel, crew, catering, and the airplane itself?",
  "Did you know military transports often use rear ramps to load vehicles and cargo?",
  "Did you know “the mains” are the main landing gear wheels?",
  "Did you know VMC means visual meteorological conditions?",
  "Did you know human-powered aircraft have flown using pedal power and very light structures?",
  "Did you know early airplanes often used wood frames and fabric covering?",
  "Did you know unmanned aircraft can be flown remotely or follow preplanned routes?",
  "Did you know PIREPs are pilot reports that share real weather encountered in flight?",
  "Did you know an ILS helps guide aircraft laterally and vertically toward a runway?",
  "Did you know a taildragger sits nose-high on the ground because its main wheels are ahead of the tailwheel?",
  "Did you know window shades may be opened for takeoff and landing so crews can assess outside conditions?",
  "Did you know keeping your seat belt loosely fastened while seated is a simple way to avoid surprise bumps?",
  "Did you know approach controllers manage aircraft arriving and departing near busy airports?",
  "Did you know Runway 07 points roughly toward 70 degrees on a compass, which is generally east-northeast?",
  "Did you know windshield strength is part of aircraft certification?",
  "Did you know smoking is banned on airline flights, but ashtrays still appear in lavatories for safety reasons?",
  "Did you know the Boeing 747 helped make long-haul international travel more accessible to more people?",
  "Did you know Class C airspace often surrounds medium-busy airports with radar approach control?",
  "Did you know taxiway centerline lights are commonly green?",
  "Did you know mixture controls adjust the fuel-air mixture in many piston airplanes?",
  "Did you know crew briefings help everyone share the same plan before takeoff and landing?",
  "Did you know a go-around is a normal safety maneuver, not a failure?",
  "Did you know pilots and controllers use UTC time so everyone works from the same clock?",
  "Did you know a NOTAM can warn pilots about closed taxiways, crane activity, or changed lighting?",
  "Did you know long flights may look curved on a flat map because Earth is round?",
  "Did you know light-sport aircraft are designed for simpler recreational flying in some countries?",
  "Did you know runways usually use magnetic direction, which is why numbers can drift over decades?",
  "Did you know track is the actual path the aircraft makes over the ground?",
  "Did you know standard operating procedures keep crews from inventing new methods under pressure?",
  "Did you know “roger” does not mean yes; it means the message was received?",
  "Did you know beacon lights warn people that an aircraft engine may be running or about to start?",
  "Did you know Concorde crossed the Atlantic much faster than subsonic airliners?",
  "Did you know a solo flight is a big milestone because the instructor stays on the ground?",
  "Did you know pilots can squawk 7600 to signal radio communication failure?",
  "Did you know fuel contamination checks help keep water and debris out of engines?",
  "Did you know “affirmative” means yes on the radio?",
  "Did you know overhead bins have weight limits even when they look roomy?",
  "Did you know airport snow removal crews often clear runways, taxiways, ramps, and lights as a coordinated operation?",
  "Did you know aircraft carriers turned airplanes into ocean-going aviation tools?",
  "Did you know a white-and-yellow beacon can identify a seaplane base?",
  "Did you know blended winglets curve upward to reduce drag on many airliners?",
  "Did you know pilots say “Romeo” for the letter R in the ICAO spelling alphabet?",
  "Did you know Class G airspace is uncontrolled airspace?",
  "Did you know a wing can stall at many speeds if the angle of attack gets too high?",
  "Did you know seat belts on airplanes are simple lap belts because they are light and effective for the job?",
  "Did you know trim tabs help reduce the force a pilot needs to hold on the controls?",
  "Did you know pushback tugs move airliners backward from gates because most jets do not reverse away from the terminal?",
  "Did you know freezing rain is especially troublesome because it can coat surfaces quickly?",
  "Did you know cockpit voice recorders record cockpit audio for accident investigation?",
  "Did you know airport terminals evolved from small buildings into complex transportation hubs?",
  "Did you know two red and two white PAPI lights usually mean the airplane is near the desired glide path?",
  "Did you know some airport fire trucks can spray foam while driving?",
  "Did you know “the pattern” means the traffic pattern around an airport, not a sewing project?",
  "Did you know oil dipsticks are part of many piston-aircraft preflight checks?",
  "Did you know the pilot flying and pilot monitoring roles can swap between flight legs?",
  "Did you know convective SIGMETs are associated with thunderstorm activity?",
  "Did you know some cockpit windows can open on the ground or at low speeds for ventilation or communication?",
  "Did you know aerobatics turned airplane control into a spectator art form?",
  "Did you know homebuilt aircraft are built by individuals under specific aviation rules?",
  "Did you know maximum landing weight can be lower than maximum takeoff weight on many large aircraft?",
  "Did you know delta wings are triangular wings often associated with high-speed aircraft?",
  "Did you know nose-loading cargo airplanes can open at the front for very long items?",
  "Did you know some modern tugs lift the aircraft nosewheel instead of using a towbar?",
  "Did you know elevators are movable tail surfaces that help the nose move up or down?",
  "Did you know pilots say “Juliett” for the letter J in the ICAO spelling alphabet?",
  "Did you know a crosswind blows across the runway instead of straight down it?",
  "Did you know the longest Wright Flyer flight on December 17, 1903 lasted 59 seconds?",
  "Did you know airspeed and groundspeed can be very different on a windy day?",
  "Did you know true altitude is height above mean sea level?",
  "Did you know “positioning flight” gets an aircraft or crew where they need to be?",
  "Did you know stabilized approach criteria help crews decide whether to land or go around?",
  "Did you know ATC vectors are headings assigned to guide an aircraft?",
  "Did you know World War I accelerated airplane development from fragile scouts to specialized military aircraft?",
  "Did you know NDBs are older radio beacons that some aircraft can still use?",
  "Did you know PAPI lights use red and white lights to help pilots judge their approach path?",
  "Did you know a concourse is a terminal area with gates branching off it?",
  "Did you know deicing boots inflate on some wings to crack and shed ice?",
  "Did you know breather holes help manage pressure between window panes?",
  "Did you know Canadian civil aircraft registrations usually start with C?",
  "Did you know waypoints are named points used for navigation?",
  "Did you know airplane wings often flex in flight because they are built to bend, not snap?",
  "Did you know a TAF is an aviation forecast for an airport area?",
  "Did you know pilots say “Hotel” for the letter H in the ICAO spelling alphabet?",
  "Did you know Bessie Coleman had to train in France because U.S. flight schools would not admit her?",
  "Did you know deplaning row by row is simple in theory and an Olympic event in practice?",
  "Did you know the horizontal stabilizer helps keep the airplane stable in pitch?",
  "Did you know airport sweepers help remove debris that could damage aircraft?",
  "Did you know pilots care about indicated airspeed because it tells them how the airplane is feeling the air?",
  "Did you know the Piper Cub is a classic light airplane associated with simple grassroots flying?",
  "Did you know anti-skid systems help keep aircraft wheels from locking during braking?",
  "Did you know cloud bases are measured above the ground at the reporting station?",
  "Did you know a go-around can be called by either pilot when a landing is not stabilized?",
  "Did you know payload is what an aircraft carries besides its own fuel and operating needs?",
  "Did you know a displaced threshold means the landing start point is moved down the runway?",
  "Did you know clearance delivery provides route clearances before many IFR flights depart?",
  "Did you know fog is basically a cloud at ground level?",
  "Did you know Runway 05 points roughly toward 50 degrees on a compass, which is generally northeast?",
  "Did you know Runway 28 points roughly toward 280 degrees on a compass, which is generally west-northwest?",
  "Did you know absolute altitude is height above the ground below?",
  "Did you know air gets thinner as altitude increases?",
  "Did you know “Speedbird” is the traditional radio call sign for British Airways flights?",
  "Did you know taildraggers have a small wheel or skid near the tail instead of a nosewheel?",
  "Did you know in the U.S., a civil aircraft must carry an airworthiness certificate and registration certificate when required by regulation?",
  "Did you know every airplane design is a compromise, because optimizing one feature can affect another?",
  "Did you know “hundred-dollar hamburger” is pilot slang for flying somewhere just to eat?",
  "Did you know the captain and cabin crew coordinate before departure so everyone knows the plan?",
  "Did you know pilots use checklists so important steps are not left to memory alone?",
  "Did you know red navigation lights are on the left side of an aircraft?",
  "Did you know “repositioning” can be the aviation version of moving the chess pieces around?",
  "Did you know the “ding” you hear in the cabin can mean different things depending on the airline and phase of flight?",
  "Did you know static wicks help bleed off static electricity from an airplane?",
  "Did you know aviation fuel grades are color-coded or labeled carefully to avoid mistakes?",
  "Did you know hot brakes may require time to cool before another takeoff?",
  "Did you know many early pilots flew without enclosed cockpits?",
  "Did you know gliders are aircraft without engines that use rising air to stay aloft?",
  "Did you know the Boeing Stratocruiser had a lower-deck lounge on some configurations?",
  "Did you know raked wingtips are swept-back wingtip shapes that can improve efficiency?",
  "Did you know flight controls are checked for free and correct movement before many flights?",
  "Did you know the word “aviation” comes from the Latin word for bird?",
  "Did you know “roger” means a transmission was received, not necessarily that the pilot agrees?",
  "Did you know boarding music is chosen by airlines to shape the mood before departure?",
  "Did you know Jet A is a kerosene-based fuel used by many turbine aircraft?",
  "Did you know EMAS beds use crushable material to help slow an aircraft that overruns a runway?",
  "Did you know hot air is less dense than cold air, which can affect takeoff performance?",
  "Did you know static ports sense outside air pressure for instruments like the altimeter?",
  "Did you know aviation weather reports are designed to pack a lot of information into short coded messages?",
  "Did you know toe brakes let pilots brake the left and right main wheels on many small aircraft?",
  "Did you know window seats get the view, aisle seats get easier movement, and middle seats build character?",
  "Did you know a modern airliner wing can look surprisingly bendy in turbulence?",
  "Did you know the throttle controls engine power in many airplanes?",
  "Did you know the Airbus A380 entered airline service in the 2000s?",
  "Did you know “firm landing” is sometimes a polite phrase for a landing everyone noticed?",
  "Did you know special liveries can celebrate sports teams, movies, anniversaries, or local culture?",
  "Did you know pilots at busy airports may receive complex taxi instructions and write them down?",
  "Did you know gusts are sudden increases in wind speed?",
  "Did you know stealth aircraft use shapes and materials that reduce radar reflections?",
  "Did you know airport windsocks show wind direction and give a rough hint of wind speed?",
  "Did you know the airspeed indicator shows how fast air is moving past the airplane?",
  "Did you know a preflight inspection helps pilots spot issues before the airplane leaves the ground?",
  "Did you know model airplanes helped many future pilots and engineers fall in love with aviation?",
  "Did you know a runway at a mountain airport can feel “shorter” to an airplane on a hot day?",
  "Did you know airport diagrams help pilots navigate on the ground?",
  "Did you know Louis Blériot crossed the English Channel by airplane in 1909?",
  "Did you know “niner” is used for the number 9 so it is not confused with the German word “nein”?",
  "Did you know a turboprop uses a turbine engine to turn a propeller?",
  "Did you know checklists became famous in aviation because they help prevent avoidable mistakes?",
  "Did you know twin tails can provide control and stability benefits on some designs?",
  "Did you know “right rudder” is a classic flight-instructor phrase in many training airplanes?",
  "Did you know codeshare flights let one airline sell seats on another airline’s operated flight?",
  "Did you know Runway 09 points roughly toward 90 degrees on a compass, which is generally east?",
  "Did you know pilots brief what they will do if something abnormal happens on takeoff?",
  "Did you know Runway 16 points roughly toward 160 degrees on a compass, which is generally south-southeast?",
  "Did you know an FBO can offer fuel, parking, lounges, and other services for private or business aircraft?",
  "Did you know small airports may have no control tower at all?",
  "Did you know “mayday” comes from the French phrase “m’aider,” meaning help me?",
  "Did you know aviation safety relies on layers, not just one magic gadget?",
  "Did you know the nosewheel is the front wheel on many tricycle-gear airplanes?",
  "Did you know a nacelle is the streamlined housing around an engine?",
  "Did you know pilots say “Victor” for the letter V in the ICAO spelling alphabet?",
  "Did you know the magnetic compass is simple, old-school, and still useful?",
  "Did you know landing gear is the wheel-and-strut system that supports the airplane on the ground?",
  "Did you know runway incursion prevention is a major airport safety focus?",
  "Did you know “greased it on” means a landing felt very smooth?",
  "Did you know a headwind can help an airplane take off in a shorter ground distance?",
  "Did you know a small airplane preflight often includes checking fuel, oil, tires, controls, and lights?",
  "Did you know airport rescue and firefighting vehicles are built to move quickly over rough ground?",
  "Did you know flight attendants secure carts because a loose cart can become a rolling hazard?",
  "Did you know bush planes are designed for rough strips, remote places, and practical utility?",
  "Did you know aircraft tail swaps can save a schedule when another airplane is available?",
  "Did you know wheel chocks are blocks that help keep parked aircraft from rolling?",
  "Did you know pilots can squawk 7500 to signal unlawful interference?",
  "Did you know airplanes are tested for loads beyond normal operations before certification?",
  "Did you know a bulk cargo hold is loaded with individual bags instead of containers?",
  "Did you know center controllers work aircraft over larger regions between airport areas?",
  "Did you know regional jets changed many smaller-city airline routes in the late 20th century?",
  "Did you know airlines care about seat pitch because every inch affects comfort and capacity?",
  "Did you know VHF radio is mostly line-of-sight, which is why altitude helps range?",
  "Did you know some early airway beacons helped guide night airmail flights across the United States?",
  "Did you know dry cabin air is one reason travelers may feel thirsty on long flights?",
  "Did you know subsonic means slower than the speed of sound?",
  "Did you know the wing root is where the wing meets the fuselage?",
  "Did you know catering, fueling, cleaning, boarding, maintenance checks, and paperwork can all overlap during a turnaround?",
  "Did you know aircraft performance calculations consider runway length, weather, weight, and obstacles?",
  "Did you know a tailwind can make takeoff and landing more challenging by increasing ground speed?",
  "Did you know supersonic means faster than the speed of sound?",
  "Did you know “squawk” comes from transponder code slang that sounds more fun than “set your beacon code”?",
  "Did you know cirrus clouds are high, wispy clouds made mostly of ice crystals?",
  "Did you know wildlife teams help keep birds and animals away from aircraft movement areas?",
  "Did you know the vertical speed indicator shows whether the airplane is climbing or descending?",
  "Did you know runway contamination can affect braking and acceleration performance?",
  "Did you know laser strikes against aircraft are dangerous and illegal in many places?",
  "Did you know the ramp or apron is where aircraft park, load, fuel, or wait?",
  "Did you know the Wright Flyer made its famous first powered flight on December 17, 1903?",
  "Did you know Runway 10 points roughly toward 100 degrees on a compass, which is generally east-southeast?",
  "Did you know a white-green-yellow beacon can identify a heliport?",
  "Did you know wake turbulence spacing keeps aircraft away from strong vortices behind larger airplanes?",
  "Did you know NOTAMs can tell pilots about temporary navigation, runway, or airspace changes?",
  "Did you know airlines swap aircraft when maintenance, weather, or scheduling requires it?",
  "Did you know cargo compartments can have smoke detection or fire suppression depending on aircraft design?",
  "Did you know “rotate” is the callout for lifting the nose during takeoff?",
  "Did you know airplanes are weighed and balanced so they handle correctly?",
  "Did you know thin air can make engines and wings work differently than they do near sea level?",
  "Did you know the safety demonstration is a mini training session passengers hear every flight?",
  "Did you know a nonstop flight goes from origin to destination without a scheduled stop?",
  "Did you know a rejected takeoff is planned for before every airline departure?",
  "Did you know priority bags are not magic, but they may be loaded for easier unloading?",
  "Did you know variable-pitch propellers can change blade angle for different phases of flight?",
  "Did you know captains have final authority for the safe operation of their aircraft?",
  "Did you know a runway number can change if Earth’s magnetic field drifts enough over time?",
  "Did you know warbird restorations can take years of skilled work?",
  "Did you know airplane lavatories use suction rather than huge amounts of water?",
  "Did you know pressurized airplanes can fly higher while keeping the cabin comfortable?",
  "Did you know logo lights shine on some airline tails so the livery is visible at night?",
  "Did you know a heavy airplane usually needs more runway than a light airplane of similar design?",
  "Did you know a fix is a defined location used for navigation?",
  "Did you know eastbound U.S. VFR cruising altitudes commonly use odd thousands plus 500 feet when the rule applies?",
  "Did you know drones are aircraft too, even when no pilot is sitting onboard?",
  "Did you know blended wing body aircraft are experimental designs that merge wing and fuselage shapes?",
  "Did you know polar routes can be useful for flights between some continents?",
  "Did you know a compass can be affected by nearby metal and electrical fields?",
  "Did you know dangerous goods rules control what can travel by air and how it must be packed?",
  "Did you know Concorde was a supersonic passenger airliner?",
  "Did you know airplanes do not need to “push off” the ground; they need air moving over the wings?",
  "Did you know IATA airport codes are the three-letter codes printed on many baggage tags?",
  "Did you know seaplanes were especially important when airports were rare?",
  "Did you know coffee and tea service depends on water tanks carried onboard the aircraft?",
  "Did you know a direct flight may keep the same flight number even if it stops along the way?",
  "Did you know aircraft lighting rules can change by operation, aircraft type, and country?",
  "Did you know Runway 23 points roughly toward 230 degrees on a compass, which is generally southwest?",
  "Did you know deicing trucks spray heated fluid to remove ice and snow before takeoff?",
  "Did you know composite materials became more common as manufacturers looked for lighter structures?",
  "Did you know fuel vents let air replace fuel as fuel leaves the tank?",
  "Did you know RNAV means area navigation, which allows flexible routing between points?",
  "Did you know placing heavy items under the seat can be safer than lifting them into an overhead bin?",
  "Did you know flight data monitoring can spot trends before they become accidents?",
  "Did you know cones around aircraft can help mark safety zones on a ramp?",
  "Did you know clouds are classified by shape and altitude?",
  "Did you know “ship number” can identify a specific aircraft inside an airline fleet?",
  "Did you know a checklist verifies that the flow was completed correctly?",
  "Did you know lift generally works upward while weight always pulls the airplane downward?",
  "Did you know bird strikes are tracked so airports and regulators can understand patterns?",
  "Did you know actuators turn hydraulic, electric, or mechanical power into movement?",
  "Did you know formation flying requires precise planning and disciplined pilots?",
  "Did you know go-arounds are normal maneuvers that protect safety margins?",
  "Did you know Runway 19 points roughly toward 190 degrees on a compass, which is generally south-southwest?",
  "Did you know approach charts are like recipes for arriving safely at a runway in reduced visibility?",
  "Did you know fly-by-wire controls became famous in modern airliners and high-performance aircraft?",
  "Did you know narrow-body airliners usually have one aisle?",
  "Did you know rivets hold many metal aircraft skins and structures together?",
  "Did you know taxiway names often use letters, such as Taxiway Alpha or Taxiway Bravo?",
  "Did you know “downwind” is the traffic-pattern leg flown parallel to the runway opposite the landing direction?",
  "Did you know jet streams are fast-moving rivers of air high in the atmosphere?",
  "Did you know airline meals are planned around storage, heating, timing, and weight?",
  "Did you know the Boeing 707 helped launch the jet age for airline passengers?",
  "Did you know jet engines are most efficient when they are designed for the mission they fly?",
  "Did you know “metal” is airline slang for aircraft capacity or aircraft operated by a carrier?",
  "Did you know the tiny hole in many passenger windows is called a breather hole?",
  "Did you know wind shear is a sudden change in wind speed or direction?",
  "Did you know a sonic boom is the sound of pressure waves from supersonic flight reaching the ground?",
  "Did you know some runway edge lights turn yellow near the far end to warn pilots that runway is running out?",
  "Did you know oil analysis can help spot engine wear trends?",
  "Did you know electric aircraft experiments are part of aviation’s ongoing search for cleaner propulsion?",
  "Did you know strobe lights make aircraft easier to see in the sky?",
  "Did you know cotter pins are small parts with a big job in keeping hardware secure?",
  "Did you know the flight management system helps airliners manage navigation and performance?",
  "Did you know “heavy” after a call sign tells ATC the aircraft has significant wake turbulence category?",
  "Did you know range is how far an aircraft can fly without refueling?",
  "Did you know flight attendants’ safety role became more recognized as airline travel matured?",
  "Did you know pilots say “Delta” for the letter D in the ICAO spelling alphabet?",
  "Did you know runway edge lights are usually white along most of the runway?",
  "Did you know main landing gear carries most of the airplane’s weight while on the ground?",
  "Did you know airline captains sit in the left seat on most transport aircraft?",
  "Did you know pilots train for engine failures, but multi-engine aircraft are designed with redundancy?",
  "Did you know the “flare” is the last little pitch-up before a normal landing?",
  "Did you know the empennage is the fancy name for the tail assembly?",
  "Did you know airmail pilots often navigated by landmarks before modern navigation aids existed?",
  "Did you know the Boeing 747 became famous as the original jumbo jet?",
  "Did you know before radio navigation, pilots often followed railroad tracks and rivers?",
  "Did you know most small training airplanes fly much slower than airliners?",
  "Did you know flight levels are altitudes based on standard pressure?",
  "Did you know flight attendants train on evacuations, fires, medical events, and security procedures?",
  "Did you know cargo aircraft may have large doors for pallets, vehicles, or oversized freight?",
  "Did you know a clearance is permission from air traffic control to do something specific?",
  "Did you know a METAR is a routine aviation weather observation?",
  "Did you know Concorde retired from commercial service in 2003?",
  "Did you know “Alfa” is spelled without the usual “ph” in the ICAO alphabet?",
  "Did you know speed brakes help some airplanes slow down without changing engine power as much?",
  "Did you know escape slides can inflate quickly during an emergency evacuation?",
  "Did you know alternate airports are planned so a flight has a backup landing option when needed?",
  "Did you know the first generation of jet airliners made long-distance travel much faster?",
  "Did you know ground markings help pilots steer without street signs or lane paint like a normal road?",
  "Did you know density altitude helps explain how the airplane performs in current air conditions?",
  "Did you know bulkhead seats are near a cabin divider or wall?",
  "Did you know gate-checked bags often happen when overhead bin space runs out?",
  "Did you know the attitude indicator shows pitch and bank, like a tiny artificial horizon?",
  "Did you know freighters are aircraft configured primarily for cargo?",
  "Did you know Runway 20 points roughly toward 200 degrees on a compass, which is generally south-southwest?",
  "Did you know unpressurized airplanes usually stay lower or require supplemental oxygen at higher altitudes?",
  "Did you know the Beechcraft Bonanza has been in production in various forms for many decades?",
  "Did you know the airport movement area is the controlled part of the airfield where clearance may be required?",
  "Did you know runways are for takeoff and landing, while taxiways are for moving around on the ground?",
  "Did you know dead reckoning uses heading, speed, time, and wind to estimate position?",
  "Did you know the sound of a radial engine is a nostalgic aviation favorite?",
  "Did you know runway condition reports help pilots know whether braking may be reduced by water, snow, or ice?",
  "Did you know runway incursions are prevented with clearances, markings, signs, lights, charts, and training?",
  "Did you know contrails form when hot engine exhaust meets very cold, moist air?",
  "Did you know in U.S. airline operations, critical phases include taxi, takeoff, landing, and most flight below 10,000 feet except cruise?",
  "Did you know a crosswind landing can make an airplane point a little sideways before touchdown?",
  "Did you know Wilbur Wright flew the longest flight of the Wrights’ first powered-flight day?",
  "Did you know airshows let the public see aircraft performance up close from the ground?",
  "Did you know the speed of sound changes with air temperature?",
  "Did you know takeoff speed is about airspeed, not just speed over the ground?",
  "Did you know “super” is used for the very largest wake turbulence category in some operations?",
  "Did you know a low-wing airplane has its wings mounted lower on the fuselage?",
  "Did you know Runway 36 points roughly toward 360 degrees on a compass, which is generally north?",
  "Did you know cabin crew cross-check doors to make sure each door is set correctly?",
  "Did you know airlines often avoid painting certain areas because paint adds weight?",
  "Did you know stalling is about the wing losing smooth airflow, not the engine stopping?",
  "Did you know commercial pilot training is about flying to a higher standard, not just flying airliners?",
  "Did you know torque wrenches matter in aviation because fasteners need the right tightness?",
  "Did you know Runway 31 points roughly toward 310 degrees on a compass, which is generally northwest?",
  "Did you know yellow signs with black letters often point pilots toward a taxiway, runway, or destination?",
  "Did you know constant-speed propellers adjust blade pitch to hold a selected RPM?",
  "Did you know clear ice can be smooth, heavy, and hard to see?",
  "Did you know aviation charts show controlled airspace with different colors and boundaries?",
  "Did you know runway choices often depend on wind direction?",
  "Did you know airworthiness means an aircraft conforms to its design and is safe to fly?",
  "Did you know “slip” is a maneuver that can increase drag and change alignment?",
  "Did you know the first air traffic controllers used flags and lights before radar screens became common?",
  "Did you know fire extinguishers on aircraft are selected for aircraft-specific fire risks?",
  "Did you know airport elevation matters because high airports have thinner air?",
  "Did you know a monoplane has one main wing set?",
  "Did you know Runway 06 points roughly toward 60 degrees on a compass, which is generally east-northeast?",
  "Did you know commercial aviation grew quickly after World War II as aircraft became larger and more reliable?",
  "Did you know pilots say “Sierra” for the letter S in the ICAO spelling alphabet?",
  "Did you know flying wings have little or no distinct fuselage or tail?",
  "Did you know instrument approaches have published minimums for visibility and altitude?",
  "Did you know runway sequencing is the art of lining up arrivals and departures efficiently?",
  "Did you know seat pitch is the distance from a point on one seat to the same point on the seat ahead?",
  "Did you know airline boarding from the left side is a long-running convention at many airports?",
  "Did you know after V1, crews normally continue takeoff unless the airplane cannot fly?",
  "Did you know hinges let control surfaces move while staying attached to the airplane?",
  "Did you know rounded airplane windows help spread pressure stress better than sharp corners?",
  "Did you know variation is the angle between true north and magnetic north?",
  "Did you know the Airbus A380 is known for having two full passenger decks?",
  "Did you know pitot heat helps keep ice from blocking the pitot tube?",
  "Did you know a ram air turbine can deploy into the airstream on some aircraft to provide emergency power?",
  "Did you know airplane cabins are pressurized because the air at cruising altitude is too thin to breathe comfortably?",
  "Did you know contrails are short for condensation trails?",
  "Did you know GPS navigation lets aircraft follow precise routes between invisible points in the sky?",
  "Did you know business jets are designed to move small groups quickly and flexibly?",
  "Did you know pilots use trim so the airplane does not need constant heavy control pressure?",
  "Did you know pilots say “November” for the letter N in the ICAO spelling alphabet?",
  "Did you know weather minima set conditions needed for certain approaches and landings?",
  "Did you know a jet bridge is the movable hallway between the terminal and the airplane?",
  "Did you know the airplane’s nose does not point exactly where the airplane is moving in every condition?",
  "Did you know a gate is the passenger doorway area where an aircraft meets the terminal?",
  "Did you know runway safety areas give extra margin around runway ends and sides?",
  "Did you know “say again” is the aviation-friendly way to ask someone to repeat a message?",
  "Did you know hypersonic flight usually means speeds above Mach 5?",
  "Did you know when an airplane banks, part of the lift helps pull it through the turn?",
  "Did you know VOR stations send radio signals aircraft can use for navigation?",
  "Did you know airport runway names use leading zeros, so runway 4 is painted as 04?",
  "Did you know crew jumpseats fold away to save space?",
  "Did you know airplanes fly because their wings help create lift as air moves around them?",
  "Did you know the seat belt sign is there because turbulence can happen unexpectedly?",
  "Did you know tomato juice has a devoted fan club on airplanes partly because savory flavors can stand out in flight?",
  "Did you know pneumatic systems use compressed air for certain aircraft functions?",
  "Did you know eVTOL aircraft use electric propulsion concepts for vertical-lift designs?",
  "Did you know IFR means instrument flight rules?",
  "Did you know night flying requires more equipment than simple daytime visual flying in many rule systems?",
  "Did you know “three greens” means landing gear indicators show the gear is down on many aircraft?",
  "Did you know just culture encourages reporting honest mistakes so the system can learn?",
  "Did you know tiltrotors can take off like helicopters and cruise more like airplanes?",
  "Did you know “wheels up” is a casual way to refer to takeoff time?",
  "Did you know aircraft deicing fluid is often brightly colored so crews can see coverage?",
  "Did you know the Wright brothers were bicycle builders before they became aviation pioneers?",
  "Did you know fixed landing gear stays down all the time and is common on many training airplanes?",
  "Did you know pilots use the word “position” to report where they are when needed?",
  "Did you know navigation lights help others see an aircraft’s orientation at night?",
  "Did you know T-tails place the horizontal stabilizer high on the vertical tail?",
  "Did you know great-circle routes are the shortest paths across a sphere?",
  "Did you know pilots say “Kilo” for the letter K in the ICAO spelling alphabet?",
  "Did you know low wings can make landing gear design and fuel placement convenient on many aircraft?",
  "Did you know amphibious airplanes can operate from both water and land when properly equipped?",
  "Did you know thrust pushes an airplane forward, while drag tries to slow it down?",
  "Did you know static bonding during fueling helps reduce spark risk?",
  "Did you know the battery provides electrical power before the engine or generators are online?",
  "Did you know visibility tells pilots how far they can see through the air?",
  "Did you know pilots say “Lima” for the letter L in the ICAO spelling alphabet?",
  "Did you know “block time” usually measures time from pushback or brake release to arrival at the gate?",
  "Did you know “deadhead” can describe crew traveling as passengers to work another flight?",
  "Did you know Lindbergh’s airplane was named Spirit of St. Louis?",
  "Did you know composite airframes can reduce weight compared with traditional metal structures?",
  "Did you know tool control helps make sure no tool is left inside an aircraft?",
  "Did you know single-engine airplanes have one engine?",
  "Did you know pilots say “Quebec” for the letter Q in the ICAO spelling alphabet?",
  "Did you know pressurized cabins made high-altitude airline travel more comfortable?",
  "Did you know thrust reversers redirect engine thrust to help slow some jets after landing?",
  "Did you know tricycle landing gear has a nosewheel and two main wheels?",
  "Did you know aircraft logbooks tell the story of maintenance, inspections, and repairs?",
  "Did you know a plane can be moving fast over the ground but still have low airspeed in a strong tailwind?",
  "Did you know boarding doors are usually armed before departure so slides can deploy in an emergency?",
  "Did you know runway end lights show red toward departing aircraft?",
  "Did you know the right side of an airliner is often busy with catering, baggage, and service vehicles?",
  "Did you know FL350 means flight level 350, or about 35,000 feet on standard pressure?",
  "Did you know “$100 hamburger” flights often cost more than $100 now, but the phrase stuck?",
  "Did you know airline call signs are often different from the company’s public brand name?",
  "Did you know U.S. civil aircraft registrations usually start with the letter N?",
  "Did you know descending does not always mean the engines are off?",
  "Did you know the loud lavatory flush is dramatic because the system uses pressure difference?",
  "Did you know a “jumpseat” is an extra crew seat, not a tiny trampoline?",
  "Did you know World War II accelerated advances in engines, navigation, radar, and aircraft production?",
  "Did you know aircraft designers balance speed, range, payload, cost, comfort, and maintenance?",
  "Did you know “hangar flying” means telling aviation stories, often with generous hand gestures?",
  "Did you know Orville Wright piloted the first 1903 Wright Flyer flight?",
  "Did you know fuel selectors let pilots choose which tank feeds the engine on many small airplanes?",
  "Did you know shock struts help absorb the forces of taxiing and landing?",
  "Did you know a jet engine works by pulling in air, compressing it, adding fuel, and pushing hot gas out the back?",
  "Did you know a canard airplane has a small lifting surface ahead of the main wing?",
  "Did you know flaps extend from the wing to add lift and drag at slower speeds?",
  "Did you know a glideslope provides up-down guidance for an instrument landing?",
  "Did you know a radial is a magnetic bearing from a VOR station?",
  "Did you know a flight director gives steering guidance on the instrument panel?",
  "Did you know controlled airspace adds communication and clearance requirements around busier areas?",
  "Did you know pilots say “Foxtrot” for the letter F in the ICAO spelling alphabet?",
  "Did you know a stabilized approach means the aircraft is configured, on path, and under control by a defined point?",
  "Did you know hub airports let airlines connect many city pairs through one central point?",
  "Did you know controllers use runway numbers in clearances so there is no guessing about which pavement is meant?",
  "Did you know point-to-point airlines focus more on nonstop service between city pairs?",
  "Did you know training airplanes are designed to be predictable and forgiving?",
  "Did you know pilots read a windsock from the fat end toward the narrow end to know where the wind is going?",
  "Did you know taste can seem different in flight because cabin pressure and dry air affect smell and taste?",
  "Did you know “gear down and locked” is one of the most comforting phrases before landing?",
  "Did you know skydiving aircraft often prioritize climb rate and big doors?",
  "Did you know black signs with yellow letters often tell pilots where they are on the airport?",
  "Did you know “down-gauge” means using a smaller aircraft on a route?",
  "Did you know runways are often grooved to help water drain away?",
  "Did you know a push-to-talk switch lets pilots transmit on the radio only when they mean to talk?",
  "Did you know cumulonimbus clouds are thunderstorm clouds with serious energy inside?",
  "Did you know Bessie Coleman was the first Black woman and first Native American woman to hold a pilot license?",
  "Did you know load planners help make sure aircraft weight and balance stay within limits?",
  "Did you know a flight management computer can calculate routes, speeds, and fuel predictions?",
  "Did you know the 747’s upper deck gave it a hump-backed profile recognized around the world?",
  "Did you know Runway 18 points roughly toward 180 degrees on a compass, which is generally south?",
  "Did you know ICAO airport codes are four-letter codes used in flight planning and operations?",
  "Did you know high wings can give good downward visibility for sightseeing and some training missions?",
  "Did you know ULD stands for unit load device?",
  "Did you know Runway 17 points roughly toward 170 degrees on a compass, which is generally south?",
  "Did you know a smooth flight is often about avoiding rough air as much as flying through it?",
  "Did you know snowplows at airports can be enormous because runways are enormous?",
  "Did you know airline pilots train in full-motion simulators for emergencies they hope never happen?",
  "Did you know many U.S. ICAO airport codes add K before the familiar three-letter code?",
  "Did you know aircraft maintenance is documented carefully because records are part of airworthiness?",
  "Did you know “final” is the leg lined up with the runway for landing?",
  "Did you know evacuation slides are inspected and packed carefully so they work when needed?",
  "Did you know Runway 35 points roughly toward 350 degrees on a compass, which is generally north?",
  "Did you know cruising altitude is chosen for weather, traffic, efficiency, and aircraft performance?",
  "Did you know kitplanes let builders assemble an aircraft from manufacturer-provided parts?",
  "Did you know laminar-flow wings are designed to keep airflow smooth over more of the surface?",
  "Did you know fuel planning includes reserves because aviation avoids running fuel down to the last drop?",
  "Did you know a closed runway may be marked with a big X?",
  "Did you know the first airline passengers sometimes sat in wicker chairs?",
  "Did you know Runway 25 points roughly toward 250 degrees on a compass, which is generally west-southwest?",
  "Did you know carry-on size limits exist partly because bins and aisles have finite space?",
  "Did you know the term “stewardess” has largely been replaced by flight attendant?",
  "Did you know Charles Lindbergh flew solo nonstop across the Atlantic in 1927?",
  "Did you know runway lights can be adjusted in brightness for night and weather conditions?",
  "Did you know a handoff happens when one controller transfers an aircraft to another controller?",
  "Did you know dew point helps show how close air is to saturation?",
  "Did you know fly-by-wire systems send pilot commands through computers instead of direct mechanical linkages?",
  "Did you know “dry lease” means an aircraft is leased without crew?",
  "Did you know motor gliders can use an engine and also soar with it off or reduced?",
  "Did you know an airliner cabin is usually pressurized to feel like being at a moderate mountain elevation?",
  "Did you know windscreens are specially built to handle pressure, impacts, and weather?",
  "Did you know using the wrong fuel type can be dangerous, so fueling is carefully verified?",
  "Did you know airplanes are quieter near the front on many jetliners because engines are often behind or below the wing?",
  "Did you know Mach number compares an aircraft’s speed with the local speed of sound?",
  "Did you know barnstormers brought flying shows to towns across America in the 1920s?",
  "Did you know the Lockheed Constellation was famous for its graceful triple-tail design?",
  "Did you know “crab” can describe pointing the nose into the wind while tracking straight over the ground?",
  "Did you know airport crews remove runway rubber buildup to keep braking performance healthy?",
  "Did you know the Learjet name became shorthand for private jet travel?",
  "Did you know Runway 15 points roughly toward 150 degrees on a compass, which is generally south-southeast?",
  "Did you know “cleared for takeoff” is a specific clearance, not a casual suggestion?",
  "Did you know a transponder code is often called a squawk code?",
  "Did you know flight control cables still move controls in many small aircraft?",
  "Did you know “mayday” is used for distress situations requiring immediate assistance?",
  "Did you know V1 is a takeoff decision speed used in multi-engine transport operations?",
  "Did you know early aviators often wore goggles because cockpits were open to wind and bugs?",
  "Did you know pilots remove snow and ice before takeoff because clean wings matter?",
  "Did you know “pan-pan” signals urgency without declaring immediate distress?",
  "Did you know “Juliett” has an extra t in the ICAO alphabet spelling?",
  "Did you know the wingtip is the outer end of the wing?",
  "Did you know engineers test aircraft for bird-impact resistance in specific areas?",
  "Did you know “more right rudder” has probably echoed through flight schools for generations?",
  "Did you know in U.S. VFR cruising above 3,000 feet above the surface, magnetic course helps determine odd or even cruising altitudes?",
  "Did you know light airplanes can feel bumps more sharply than heavy airliners?",
  "Did you know a towbar connects many tugs to an aircraft nose gear during pushback?",
  "Did you know wood is still used in some classic, homebuilt, and specialty aircraft?",
  "Did you know Runway 34 points roughly toward 340 degrees on a compass, which is generally north-northwest?",
  "Did you know the Antonov An-225 was built to carry extremely large cargo?",
  "Did you know a propeller is basically a rotating wing?",
  "Did you know a vapor cone can appear around fast aircraft in humid air, even below the speed of sound?",
  "Did you know aviation museums preserve aircraft that would otherwise disappear from history?",
  "Did you know flight data recorders store technical information about the flight?",
  "Did you know a red-eye flight usually travels overnight?",
  "Did you know “standby” means wait and do not immediately reply?",
  "Did you know temporary flight restrictions can pop up for VIP movements, disasters, or major events?",
  "Did you know avgas is used by many piston-engine airplanes?",
  "Did you know a delayed inbound aircraft can delay the next outbound flight because the same airplane is continuing onward?",
  "Did you know the first Wright Flyer flight lasted about 12 seconds?",
  "Did you know airliner oxygen masks are designed to start oxygen flow when pulled down?",
  "Did you know catering trucks can rise up to meet an aircraft galley door?",
  "Did you know airplane doors are engineered so cabin pressure helps seal many plug-type doors in flight?",
  "Did you know wing loading compares an aircraft’s weight with its wing area?",
  "Did you know VFR flight following gives pilots extra traffic advisories when ATC workload allows?",
  "Did you know the auxiliary power unit is a small onboard turbine that can provide electrical power and air on the ground?",
  "Did you know aircraft cabins can feel dry because high-altitude outside air contains little moisture?",
  "Did you know lenticular clouds can form near mountains and signal strong wave activity?",
  "Did you know ultralights are very small, simple aircraft under specific national rules?",
  "Did you know density altitude is a way to describe how the airplane performs in the air it actually has?",
  "Did you know aircraft parts can have serial numbers and traceability requirements?",
  "Did you know a windsock pointing down the runway can be very good news for takeoff or landing?",
  "Did you know some airlines allow cockpit visits on the ground when crew workload and rules allow?",
  "Did you know a sterile cockpit means crews avoid nonessential chatter during critical phases of flight?",
  "Did you know a missed approach is a planned safety path, not improvisation?",
  "Did you know “wilco” means will comply?",
  "Did you know the vertical stabilizer helps keep the airplane pointed steadily through the air?",
  "Did you know pilots use call signs so ATC knows exactly which aircraft is talking?",
  "Did you know slats can extend from the front of a wing to help it fly slower before stalling?",
  "Did you know “equipment change” usually means the airline swapped the aircraft type?",
  "Did you know a private pilot certificate lets someone fly for personal reasons under specific rules?",
  "Did you know V-tails combine horizontal and vertical tail functions into two angled surfaces?",
  "Did you know Runway 21 points roughly toward 210 degrees on a compass, which is generally southwest?",
  "Did you know fuel drains let pilots sample fuel for water or contamination before flight?",
  "Did you know “avgeek” is a friendly term for someone who loves aviation?",
  "Did you know first officers are fully trained pilots, not apprentices?",
  "Did you know “short final” means the aircraft is close to the runway on final approach?",
  "Did you know glass cockpits replaced many round analog gauges with electronic displays?",
  "Did you know circuit breakers protect aircraft electrical circuits from overloads?",
  "Did you know mechanics are licensed or certified under national aviation rules?",
  "Did you know straight wings are common on slower aircraft because they can be efficient and simple?",
  "Did you know an airplane needs airflow over its wings before the wings can do their best work?",
  "Did you know certification testing can include cold, heat, vibration, lightning, and evacuation demonstrations?",
  "Did you know safety wire helps keep certain fasteners from loosening?",
  "Did you know large airports can have complex taxi routes that look like a small city map?",
  "Did you know paint can add hundreds of pounds to a large airplane?",
  "Did you know icing can change the shape of a wing and reduce performance?",
  "Did you know Runway 26 points roughly toward 260 degrees on a compass, which is generally west?",
  "Did you know a missed approach is a published path to follow when an instrument landing cannot be completed?",
  "Did you know “the nose” can mean the front of the aircraft or the direction it points?",
  "Did you know drones brought aviation technology to photographers, farmers, inspectors, and hobbyists?",
  "Did you know the Douglas DC-3 helped make passenger air travel more practical in the 1930s?",
  "Did you know a high-wing airplane has its wings mounted above the fuselage?",
  "Did you know Runway 04 points roughly toward 40 degrees on a compass, which is generally northeast?",
  "Did you know airline turnarounds are timed carefully so the airplane can leave again on schedule?",
  "Did you know airplanes can glide even without engine power because wings keep producing lift while moving through air?",
  "Did you know the call button is useful, but it is not a flight-attendant teleportation device?",
  "Did you know HF radio can carry long-distance voice communication across oceans?",
  "Did you know a runway marked 09 at one end is usually marked 27 at the other end?",
  "Did you know Runway 24 points roughly toward 240 degrees on a compass, which is generally west-southwest?",
  "Did you know spoilers can pop up on the wing to reduce lift and add drag?",
  "Did you know mountain waves can let gliders climb to impressive heights?",
  "Did you know wings are shaped to make air flow smoothly over and under them?",
  "Did you know separation standards keep aircraft apart vertically, laterally, or by time?",
  "Did you know bare-metal liveries were once popular partly because they saved paint weight?",
  "Did you know a wingtip vortex is a swirling trail of air left behind by lift?",
  "Did you know seatbacks are upright for takeoff and landing to preserve space for evacuation?",
  "Did you know borescope inspections let mechanics look inside engines without taking them fully apart?",
  "Did you know tankers refuel other aircraft in flight?",
  "Did you know flying boats once carried passengers across oceans before long concrete runways were common?",
  "Did you know winglets help reduce drag from wingtip vortices on many aircraft?",
  "Did you know combi aircraft carry both passengers and cargo on the main deck in some configurations?",
  "Did you know autopilot can hold headings, altitudes, or routes, but pilots still manage the flight?",
  "Did you know Runway 29 points roughly toward 290 degrees on a compass, which is generally west-northwest?",
  "Did you know hold-short lines tell pilots where to stop before entering a runway?",
  "Did you know ground control usually manages aircraft moving on taxiways and ramps at towered airports?",
  "Did you know aerial firefighting aircraft can drop water or retardant on wildfires?",
  "Did you know flaps help many airplanes fly more slowly for takeoff and landing?",
  "Did you know many airliner tires are filled with nitrogen because it is stable and contains little moisture?",
  "Did you know Harriet Quimby crossed the English Channel by airplane in 1912?",
];
